title: My configured title
description: My configured description
baseurl: "/Files/Pages" # Set the baseurl if your site is hosted under a subpath

# # Configure the plugins and other settings as needed
# theme: jekyll-theme-minimal
# theme: jekyll-theme-minimal
# remote_theme: "jekyll/minima"

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-sitemap