title: My GitHub Pages Site
theme: jekyll-theme-minimal

# Set the baseurl if your site is hosted under a subpath
baseurl: "/Files/Pages"

# Configure the plugins and other settings as needed

remote_theme: "jekyll/minima"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
